### ISSUE TITLE
[BUG]  Cannot find module 'react' or its corresponding type declarations

### ISSUE THREAD

**Issue by sysmat** [motiondivision/motion#3259]
1. after upgrade from 12.17.0 -> 12.17.3
2. When angular compile :  Cannot find module 'react' or its corresponding type declarations
```
Application bundle generation failed. [5.128 seconds]

X [ERROR] TS2307: Cannot find module 'react' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/motion-dom/dist/index.d.ts:2:26:
      2 │ import { RefObject } from 'react';
        ╵                           ~~~~~~~
```
**5. Expected behavior**

This lib must be agnostic

**Comment by mattgperry** [comment]
🤦‍♂️annoying this built. Thanks for the report I’ll take a look

**Comment by mattgperry** [comment]
Fixed in `12.18.0`

**Comment by sysmat** [comment]
the problem is same 12.18.0, maybe peerDependencies


```
Error: node_modules/.pnpm/motion-dom@12.17.3/node_modules/motion-dom/dist/index.d.ts:2:27 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

2 import { RefObject } from 'react';
                            ~~~~~~~
```

**Comment by sysmat** [comment]
reproduction: https://stackblitz.com/edit/stackblitz-starters-qdtgjbx8?file=demo%2Fpackage.json

**Comment by mattgperry** [comment]
Weird that didn’t update the motion-dom package - you can see it’s requesting 12.17.3 still. I’ll take a look

**Comment by mattgperry** [comment]
Can you try `12.18.1`?

**Comment by sysmat** [comment]
it works with 12.18.1, @mattgperry thx
